"use client";
import {useMemo,useState} from "react";
const base=[
["Frango crocante","🍗","Almoço",18,298,"#F3C45B"],["Bolinho de batata-doce","🍠","Lanches",16,186,"#E76F2E"],["Brownie proteico","🍫","Doces",12,142,"#BC6A40"],["Omelete de cestinha","🍳","Café",10,164,"#F6D978"],["Tilápia com limão","🐟","Jantar",15,220,"#8CB9A5"],["Chips de abobrinha","🥒","Lanches",11,96,"#9BBB62"],["Pão de queijo fit","🧀","Café",14,128,"#F1B441"],["Almôndega leve","🥩","Almoço",17,264,"#C96C50"],["Banana com canela","🍌","Doces",9,118,"#E7B64C"],["Tofu douradinho","🌱","Veggie",13,192,"#88A95C"],["Camarão picante","🍤","Jantar",10,178,"#E98762"],["Granola crocante","🥣","Café",12,154,"#D29A57"]] as const;
const suffix=[""," especial"," express"," com ervas"," super crocante"," leve"," da casa"," zero farinha"," proteico"];
const recipes=Array.from({length:108},(_,i)=>{const b=base[i%12],n=Math.floor(i/12);return{id:i+1,name:b[0]+suffix[n],emoji:b[1],cat:b[2],time:b[3]+n%3,kcal:b[4]+n%4*7,color:b[5]}});
const cats=["Todos","Café","Almoço","Lanches","Jantar","Doces","Veggie"];
export default function Home(){const[cat,setCat]=useState("Todos"),[q,setQ]=useState(""),[fav,setFav]=useState<number[]>([]),[tab,setTab]=useState("Início"),[limit,setLimit]=useState(12),[pick,setPick]=useState<(typeof recipes)[0]|null>(null);const list=useMemo(()=>recipes.filter(r=>(cat==="Todos"||r.cat===cat)&&r.name.toLowerCase().includes(q.toLowerCase())),[cat,q]);const shown=tab==="Salvos"?recipes.filter(r=>fav.includes(r.id)):list;const toggle=(id:number)=>setFav(f=>f.includes(id)?f.filter(x=>x!==id):[...f,id]);return <main>
<header><button className="brand"><i>AF</i><b>AIR FRYER<br/>FIT</b></button><button className="avatar">LF</button></header>
{tab==="Início"&&<><section className="hero"><small>SEU NOVO JEITO DE COMER BEM</small><h1>Crocante.<br/>Leve. <em>Fácil.</em></h1><button onClick={()=>document.querySelector(".content")?.scrollIntoView()}>VER RECEITAS ↓</button><div className="plate">🍗</div><div className="badge"><b>+100</b><span>RECEITAS</span></div></section><section className="stats"><div><b>108</b><span>receitas</span></div><div><b>≤ 20</b><span>minutos</span></div><div><b>100%</b><span>air fryer</span></div></section></>}
<section className="content"><div className="title"><div><small>{tab==="Salvos"?"SUA COLEÇÃO":"ESCOLHA E PREPARE"}</small><h2>{tab==="Salvos"?"Receitas salvas":"Bora cozinhar?"}</h2></div><i>{shown.length}</i></div><label className="search">⌕<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar receita..."/><b>108</b></label>{tab!=="Salvos"&&<div className="chips">{cats.map(c=><button className={cat===c?"on":""} onClick={()=>{setCat(c);setLimit(12)}} key={c}>{c}</button>)}</div>}
{shown.length?<><div className="grid">{shown.slice(0,limit).map(r=><article key={r.id} onClick={()=>setPick(r)}><div className="art" style={{background:r.color}}><span>{r.emoji}</span><small>{r.cat}</small></div><div className="copy"><h3>{r.name}</h3><p><span>◷ {r.time} min</span><span>⚡ {r.kcal} kcal</span></p></div><button className={fav.includes(r.id)?"heart liked":"heart"} onClick={e=>{e.stopPropagation();toggle(r.id)}}>{fav.includes(r.id)?"♥":"♡"}</button></article>)}</div>{shown.length>limit&&<button className="more" onClick={()=>setLimit(x=>x+12)}>MOSTRAR MAIS <b>+12</b></button>}</>:<div className="empty">🍽️<h3>Nada por aqui ainda</h3><p>Toque no coração para salvar.</p></div>}</section>
<nav><button className={tab==="Início"?"active":""} onClick={()=>setTab("Início")}>⌂<span>Início</span></button><button className="find" onClick={()=>{setTab("Início");document.querySelector(".content")?.scrollIntoView()}}>⌕</button><button className={tab==="Salvos"?"active":""} onClick={()=>setTab("Salvos")}>♡<span>Salvos</span></button></nav>
{pick&&<div className="modal" onClick={()=>setPick(null)}><section onClick={e=>e.stopPropagation()}><div className="modalArt" style={{background:pick.color}}><button onClick={()=>setPick(null)}>×</button><span>{pick.emoji}</span><b>{pick.cat}</b></div><div className="body"><div className="recipeTitle"><div><small>RECEITA #{String(pick.id).padStart(3,"0")}</small><h2>{pick.name}</h2></div><button onClick={()=>toggle(pick.id)}>{fav.includes(pick.id)?"♥":"♡"}</button></div><div className="facts"><span><b>{pick.time}</b>min</span><span><b>{pick.kcal}</b>kcal</span><span><b>28g</b>proteína</span></div><h4>INGREDIENTES</h4><ul><li>1 porção do ingrediente principal</li><li>1 colher de azeite</li><li>Sal, ervas e temperos</li></ul><h4>PREPARO</h4><ol><li>Misture tudo em uma tigela.</li><li>Acomode no cesto sem sobrepor.</li><li>Asse a 180°C por {pick.time} min.</li><li>Sirva douradinho.</li></ol><button className="cook" onClick={()=>setPick(null)}>PRONTO, VOU FAZER! 🔥</button></div></section></div>}</main>}
